import React, { useState, useEffect } from 'react';
import axios from 'axios';

export default function ReportPage({ onTrigger, pipeline }) {
  const [report, setReport]   = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchReport = async () => {
    try {
      const res = await axios.get('/api/report?type=summary');
      setReport(res.data.data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReport();
    const t = setInterval(fetchReport, 5 * 60 * 1000);
    return () => clearInterval(t);
  }, []);

  // Refresh after pipeline finishes
  useEffect(() => {
    if (pipeline?.last_run_status === 'success') {
      setTimeout(fetchReport, 2000);
    }
  }, [pipeline?.last_run_status]);

  const fmt = (ts) => {
    if (!ts) return 'Never';
    try {
      return new Date(ts).toLocaleString('en-GB', {
        day: '2-digit', month: 'short', year: 'numeric',
        hour: '2-digit', minute: '2-digit',
      });
    } catch { return ts; }
  };

  const busy = pipeline?.running;

  const statusColor = { never: 'var(--text-muted)', running: '#ffcc00', success: '#00ff88', }[pipeline?.last_run_status] || 'var(--text-muted)';
  const statusIcon  = { never: '○', running: '◉', success: '●' }[pipeline?.last_run_status] || '○';

  return (
    <div>
      <div className="page-title">AI Market Report</div>
      <div className="page-subtitle">Generated by GPT-4o-mini from live Reddit + CoinGecko data</div>

      {/* Pipeline control */}
      <div className="card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
        <div>
          <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginBottom: 4 }}>Pipeline Status</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ color: statusColor, fontSize: 14 }}>{statusIcon}</span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>
              {busy ? 'Running now...' : pipeline?.last_run_status || 'Never run'}
            </span>
            {pipeline?.last_run_at && (
              <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>— {fmt(pipeline.last_run_at)}</span>
            )}
          </div>
        </div>
        <button
          className={`trigger-btn ${busy ? 'running' : ''}`}
          onClick={onTrigger}
          disabled={busy}
          style={{ padding: '9px 22px', fontSize: 13 }}
        >
          {busy ? <><span className="spinner"/> Analysing...</> : '▶  Run Full Analysis'}
        </button>
      </div>

      {loading ? (
        <div className="loading-state"><div className="dots"><span/><span/><span/></div><div>Loading report...</div></div>
      ) : !report ? (
        <div className="empty-state">
          <div className="empty-icon">📋</div>
          <div style={{ marginBottom: 8 }}>No report yet.</div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', maxWidth: 400 }}>
            Click "Run Full Analysis" to generate your first report. The pipeline will fetch Reddit posts,
            analyse sentiment, detect trends, correlate with prices, then write this report.
          </div>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>

          {/* Summary */}
          <div className="card">
            <div className="card-title">Executive Summary</div>
            <p style={{ fontSize: 15, lineHeight: 1.9, fontFamily: 'var(--font-display)', fontWeight: 400 }}>
              {report.content || 'No summary available.'}
            </p>
            <div style={{ marginTop: 10, fontSize: 11, color: 'var(--text-muted)' }}>
              Generated {fmt(report.generated_at)}
            </div>
          </div>

          {/* Key insights */}
          {report.key_insights?.length > 0 && (
            <div className="card">
              <div className="card-title">Key Insights</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
                {report.key_insights.map((insight, i) => (
                  <div key={i} style={{
                    display: 'flex', gap: 12, padding: '11px 13px', borderRadius: 8,
                    background: 'var(--bg-raised)', border: '1px solid var(--border)',
                    fontSize: 13, lineHeight: 1.6,
                  }}>
                    <span style={{ color: '#00ff88', fontFamily: 'var(--font-mono)', fontSize: 11, minWidth: 22, paddingTop: 2 }}>
                      {String(i + 1).padStart(2, '0')}
                    </span>
                    <span>{insight}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Coins mentioned */}
          {report.coins_mentioned && (
            <div className="card">
              <div className="card-title">Coins Mentioned</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 7 }}>
                {report.coins_mentioned.split(',').filter(Boolean).map(coin => (
                  <span key={coin} style={{
                    padding: '4px 12px', borderRadius: 999,
                    background: 'var(--bg-raised)',
                    border: '1px solid var(--border-bright)',
                    fontSize: 12, fontFamily: 'var(--font-mono)',
                  }}>{coin.trim()}</span>
                ))}
              </div>
            </div>
          )}

          {/* How it works */}
          <div className="card" style={{ borderStyle: 'dashed' }}>
            <div className="card-title">How This Report Is Generated</div>
            <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.9 }}>
              {[
                ['01', 'n8n fetches top posts from 4 subreddits every hour via public Reddit JSON API'],
                ['02', 'Agent 1 scores each post with GPT-4o-mini: topic + sentiment -1.0 to +1.0'],
                ['03', 'Agent 2 groups topics by mention frequency, calculates momentum scores'],
                ['04', 'Agent 3 fetches live prices from CoinGecko, correlates sentiment with price movement'],
                ['05', 'Agent 3 labels each coin HOT / COOLING / NEUTRAL and writes this report'],
              ].map(([n, t]) => (
                <div key={n} style={{ display: 'flex', gap: 12, marginBottom: 4 }}>
                  <span style={{ color: '#00ff88', fontFamily: 'var(--font-mono)', minWidth: 22 }}>{n}</span>
                  <span>{t}</span>
                </div>
              ))}
            </div>
          </div>

        </div>
      )}
    </div>
  );
}
